### ISSUE TITLE
Jetpants sharded_tables example in configuration needs further nesting.

### ISSUE THREAD

**Issue by grahamc** [tumblr/jetpants#26]
https://github.com/tumblr/jetpants/blob/master/etc/jetpants.yaml.sample#L46-L59

The example results in errors  when doing a shard cutover, digging reveals it should probably be:

```
sharded_tables:
    shardname:
        tablename:
            sharding_key: user_id
            chunks: 200
```
